### ISSUE TITLE
Missing LICENSE file in the repo of ver 0.0.2

### ISSUE THREAD

**Issue by itsuki-murata** [component/throttle#9]
Currently I'm using throttleit version 0.0.2, but can't find a LICENSE file in the repo of ver 0.0.2.
Could you add the LICENSE file in the repo of ver 0.0.2?
Or is it possible to use the LICENSE file of the latest version as the license for ver 0.0.2?
Thanks in advance.

**Comment by sindresorhus** [comment]
It's not feasible to update that old of a version. I suggest updating to the latest version.

**Comment by itsuki-murata** [comment]
Thank you for the advice.
I'll consider upgrading to the latest version.
